### ISSUE TITLE
订单功能完善

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#10]
现在订单页面下的：我的订单，这个页面，订单被列表形式展示出来，需要做的修改是订单编号，这个编号是一个链接，可以点开查看这个订单的详情页，因为有的客户地址是很长的，挤在这一行里面会看的人很眼晕，如果有10行客户的这种订单，发货的人很容易看混了，这行看到那行，所以请做成链接，可以点订单链接打开一个新窗口，上面有详细的全部资料，包括地址，在这个大页面里面，地址哪里就显示个6-8个文字，其他的就省略就行，千万别全显示出来，会很乱的。

可以和修改项的那个弹窗做一个整合，就是把客户信息那套东西也做到那个弹窗新页面里去。

**Comment by xiaoweiqb** [comment]
能截图说一下吗？有点不懂呢

**Comment by xiaoweiqb** [comment]
哦，再看了一下，客户的信息放弹窗里面
