### ISSUE TITLE
关于产品编号的问题

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#11]
如果之前有新建的产品，当删除掉以后，编号也会随之被绑定无法使用了，比如现在的界面，编号是从6开始的，而不是从1，因为我们之前删除过5个商品，新建商品也不可以修改编号，编号也不顺延，被删除的产品编号没有得到释放。

**Comment by barrowcom** [comment]
现在后台编辑上传商品，列表的第一个产品的序列号实际是61，而不是1

**Comment by xiaoweiqb** [comment]
我建议采用这个系统编号，因为这个是系统唯一的，以后，你们记一个产品，可以很快的定位到是哪个产品，如果一个产品的编号每页都是0-10这样存在，以后中间删减以后，这个数字全系统就会变，而且不利于定位唯一，所以我建议保留。
