### ISSUE TITLE
添加产品资料项缺少颜色

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#12]
颜色

需要有颜色对话框，并且支持输入保存，比如我们可以保存”白色/银色/红色/黑色 这些颜色信息，等添加其他产品的时候，不用手工的再打字这些颜色，可以直接进行选取，这样比较方便好用。

**Comment by xwqb** [comment]
现在为了能尽快能让这个平台运作起来，我们预订一些颜色的下拉列表来做吧，这个优化的问题我们先放后，好么？先保证功能有，然后在说优化，如果一来就把某个功能想象得太完美的话，做起来是非常花时间的！希望你能理解程序员的痛苦！
