### ISSUE TITLE
关于导出的表格格式样式文件的注解

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#13]
![qq 20150528094449](https://cloud.githubusercontent.com/assets/12635228/7851136/bf4db5b6-051d-11e5-880f-d0510db03ef7.png)

简单来说，最左侧的货品代码那里，在我们的进销存软件里面实际用途为0，但是导入格式里面，这个项目必须要有，但是我们页面转化到这个表格的时候，这个项下的所有内容，都是空的。

然后是“品名规格”，这个是这个表格最最重要的地方，生成这个品名规格，实际需要采集网站的3个数据组合而成的，分别是“颜色+产品名+型号”，关于产品名这里要着重说一下，因为产品名称是有2个方向性的，有时候我们为了表达清晰和让客户容易理解，在网站上面，给客户的品名有可能是缩短或者加长的，但是在我们自己的进销存端，就是我们公司内如，这个产品名可能就会比较复杂，但是智慧记的进销存软件导入规则里面，就是和我们软件里面的名称必须只字不差，连空格都不能差，否则导入的时候就会失败，我想解决这个问题最好的办法，就是在添加产品信息的时候，有2个产品名称的录入对话框，一个呢，是网站前端显示出来的，一个呢，是我们进销存软件导入的完全版的产品名，这样在设计这个转换文件程序的时候，采集的数据就是颜色+第2个完整版的产品名+型号  ，至于第一个网站前端的品名，是不被转换表格文件的数据采集所使用的。这样描述可以理解吗？

**Comment by barrowcom** [comment]
继续讲货品类别，这个项目

首先，在网站端，我们会有产品分类，一级大类，一级大类里又有二级分类，方便产品管理和客户更方便的找到产品订货，但是在我们进销存软件这一端，只有一级大类，是没有二级大类的，所以这个货品类别这个项，采集数据的约束条件就是只采集这个产品的一级大类名称进行收集，不要具体到二级分类。

**Comment by barrowcom** [comment]
至于库存数量，最低库存，最高库存，这3项，实际生成的数据都是0就可以

**Comment by barrowcom** [comment]
这个表格带星号的就是必须填写的项，就是品名规格和数量这2个关键的

**Comment by xiaoweiqb** [comment]
明白了，你们要导入智慧记的表格的品名需要是一个更复杂的品名，然后，这个品名呢在网页前端不需要显示很复杂的给用户，所以，你需要一个系统名字来标注，这个系统名字用于导出的excel的表格能被智慧记软件识别，这个需要导入智慧记的品名就是颜色+系统品名+型号，这样，你们的智慧记系统才会读取这个品名，是这样吗？

**Comment by barrowcom** [comment]
是的，一个是给用户看的简介明了的品名，一个是和我们电脑智慧记的数据库里面的复杂品名一致的，这个我们后期数据录入的时候会自行保证准确率，错一个字都导入不进去
