### ISSUE TITLE
缺少会员注册审核功能

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#14]
因为我们这个是一个授权经销商的批发端订货平台，不能随便人注册都可以进来看到产品信息包括敏感报价这些资料，这个注册审核功能就很重要

功能主要是用户提交注册申请，我们人工审核，用户填写一个注册表单，我们人工点通过审核和不通过审核，

再就是设定用户级别，简单来解释，我们的客户分为3类“1级代理商，他们的价格最低的，2级经销商，他们的价格是中等的，3就是普通零售客户，他们的就是零售价，我们给他选择到什么级别，到时候这个客户在他的页面下看到的价格和生成的价格就是按照对应的价格级别显示和计算出来的

当然这个用户级别，后期也要在会员管理里面进行修改，因为有的零售客户也可能成为我们的2级经销商，二级经销商也有可能成为1级代理商。都需要灵活更改的。

**Comment by xiaoweiqb** [comment]
这个功能在后台管理的会员管理中可以看到

**Comment by xiaoweiqb** [comment]
但是分级的经销商的还没有
