### ISSUE TITLE
产品信息价格需要完善

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#15]
产品信息里面需要添加3个价格，支持3个用户组的不同定价体系，分别是1级代理商单价   2级经销商单价  零售客户单价

**Comment by xwqb** [comment]
哥们，这个功能当时好像没说吧！

**Comment by barrowcom** [comment]
我查了一下确实没说，那这个优化功能如果你不想做的话可以不做。

**Comment by xiaoweiqb** [comment]
嗯，我的意思是说，先把当时涉及到的功能完成，后续如果我有时间的话，可以帮你搞搞！！
