### ISSUE TITLE
用户端的购物车功能

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#16]
用户端的购物车，因为在后台上传新产品的时候，没有颜色选项，我们添加了颜色选项以后，用户端这里的购物车就会出现一个问题，就是不同颜色的同一个产品如何进行显示和排序的问题，

我的意见是 产品名称表格前面多列，多一个颜色列，这个颜色表格里面显示出颜色名称来，比如张三采购了一个名称为  ABC接头  的产品，他买了白色，红色，绿色 这3个颜色，那么实际显示在购物车里面的，就是3行内容，而不是一行内容里面挤着3个颜色，并且这个颜色的字体要加粗显示，方便客户看。

排序的规则呢，就是不同颜色但是相同品名的产品会被就近排列，而不要岔开，要挨着。

**Comment by xwqb** [comment]
排序以相同品名排序是吧？

**Comment by barrowcom** [comment]
用户端购物车功能优化我们最后进行，先把管理端搞定。
