### ISSUE TITLE
左侧导航栏空白区域大，可以优化

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#22]
![qq 20150608191003](https://cloud.githubusercontent.com/assets/12635228/8033517/a691f684-0e11-11e5-9a10-f4311409bbd1.png)

![qq 20150608191107](https://cloud.githubusercontent.com/assets/12635228/8033529/bf7e0db8-0e11-11e5-823e-95b61d981002.png)

**Comment by barrowcom** [comment]
现在还是右侧空余位置过大，麻烦再瘦身一下

**Comment by xiaoweiqb** [comment]
左侧还是右侧?

**Comment by barrowcom** [comment]
左侧，打错字了，右侧没有导航栏
