### ISSUE TITLE
缺少产品分类管理

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#3]
产品无法进行分类，会导致所有产品都在一个列表下，管理和查看都比较混乱，随着产品数量不断增加，会更难管理和区分产品

**Comment by xwqb** [comment]
好的，我会添加一个功能：在提交产品的时候选择产品分类，然后产品分类可以进行管理

**Comment by barrowcom** [comment]
产品分类有了，但是不支持2级分类，还有一个BUG，是在用户端那里，当用户进入产品列表以后，开始显示的是全部商品，但是当用户选择了某一类别选购完想返回那个全部商品的页面就找不到了，你可以实际使用体验一下这个问题。

**Comment by barrowcom** [comment]
用户端那里的问题暂时先不管了，先把管理端搞好再弄那边，这边搞不顺，那边也不能一次修改到位。
