### ISSUE TITLE
关键BUG，导出的表格格式有错误

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#34]
![0022](https://cloud.githubusercontent.com/assets/12635228/8178098/d4b847c0-143d-11e5-9041-0d5110e76e86.png)

我们输入的系统名称是没有错的，（三分手拧型宝塔接头 TB3C-C02）

但是表格导出的，就是（TB3C-C02三分手拧型宝塔接头）

分析格式，白色+空格 （没错）
系统名称，出错了，而且中间的空格也没了，导致我们导入到进销存软件的时候失败

好像这个导出表格的功能并没有对“系统名称”进行选取，而是对产品名称和型号进行了选取，并默认排序为颜色空格+型号+产品名称 

这个格式问题请麻烦尽快改好。

**Comment by barrowcom** [comment]
另外关键性数据补充提示，智慧记软件升级了，升级后的软件要求输入的表格里面的单价要有实际数据，如果没数据，导入的资料也将没有单价，所以，亲，麻烦你把单价这项也采集一下数据，就是采集单价那里的数据，千万别采集建议零售价。

**Comment by barrowcom** [comment]
这个是一个意外情况。。很抱歉

**Comment by xwqb** [comment]
我已经改了，你测下试试
