### ISSUE TITLE
客户添加到购物车这个功能的一些不便

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#38]
![002](https://cloud.githubusercontent.com/assets/12635228/8197692/ee736862-14cd-11e5-995e-ab7875381e3e.png)

A。当在产品列表进行选购产品添加购物车进行操作的时候，发现2个问题，1是同样一个产品，比如黑色，我填写了10个，成功添加到了购物车，然后我需要再黑色增加10个，就会提示出现错误，说数据已存在，这个问题就只能到购物车界面按修改的方式进行添加，不能累计添加，如果频繁切换购物车会造成很多不便，如果客户把一个产品列表的订单都下完，再去购物车想增加这一项，有可能就忘了某一个产品需要加一些了，因为客户下单存在一个随机想法，尽量是允许累计增加，1是方便客户，2是提高我们潜在销售能力。

B.当同一个产品选择了某一个颜色并输入了数量以后，这个颜色的产品被添加到了购物车，比如A产品我要黑色，输入20，被加入了购物车，我还是A产品，选择白色，这时候，刚才选择黑色的20这个数字，还是在那个输入框里，我一点输入框或者其他位置，这20个白色就被加入到购物车了，不管我是不是要20个，都进去了，通过这几天的实际体验，发现这个输入数字点击任意位置即加入购物车的功能非常容易造成误操作，也让第一次进入系统的人有摸不着头脑，请在“操作”这一列，填写数量的对话框后面，增加一个实体的”加入购物车“的按钮，当作确认键，这样更容易被大部分人接受，并降低误操作率

**Comment by xwqb** [comment]
易订网上不就是这样操作的吗？为什么现在有了这种操作方式，有要求改回来?
