### ISSUE TITLE
ADMIN管理端的会员管理功能加强

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#39]
现在的管理功能过于简单，只有审核和冻结的按钮功能

需要在这个界面多一个编辑按钮，点击编辑按钮出现的界面里面，能让我们可以看到用户注册时候的所有资料，包括用户名，用户密码，邮箱，地址等所有信息都可见，并且都可以进行编辑操作，当然如果我们有权限更改用户名在实际程序制作过程中难度较大的话可以没有更改用户名的权限，但是其他的都要有可完全编辑修改的权限。

**Comment by barrowcom** [comment]
![hy](https://cloud.githubusercontent.com/assets/12635228/8198103/65a681a2-14d4-11e5-924e-586f4431fa99.png)

现在的会员管理

**Comment by xwqb** [comment]
晕死，这也要编辑？
