### ISSUE TITLE
上传商品图片的页面里面，这个上传按钮不太明显，和旁边的注释都是蓝色的字体背景，挨的也很近，麻烦分行，方便操作

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#4]
![qq 20150523144629](https://cloud.githubusercontent.com/assets/12555691/7782745/279370ce-015a-11e5-86a3-77f10b201437.png)

**Comment by zhongjia** [comment]
还有上传图片以后，左侧这里大图预览这里，有一个选择框，默认的范围只是左上角，需要手工拉到全部选择到才可以，万一上传资料的时候忘记，就容易造成误操作，能否创建一个快捷功能，让直接就图片默认是满画布选取框，如果我们需要缩小范围，再手动调整，这样不容易出错。

**Comment by xwqb** [comment]
恩，OK
