### ISSUE TITLE
首页登录的显示错误

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#42]
![01](https://cloud.githubusercontent.com/assets/12635228/8227568/13cd4a02-15db-11e5-923b-97a7cdbfd56a.jpg)

上图为高分辨率显示状态下的首页状态

![02](https://cloud.githubusercontent.com/assets/12635228/8227575/250ea3c4-15db-11e5-99e8-f7b67771a97b.png)

上图为低分辨率显示状态下的首页状态

低分辨率下，登录窗口显示不出来。

还有你打算首页的布局是怎么设计的，还有英语登录的界面在哪里出现，做这个修改以前我们可否先沟通一下，争取一次过不要做2次修改。

**Comment by xiaoweiqb** [comment]
英文的还早呢，这个是要做配置测试的，现在我还没做修改

**Comment by barrowcom** [comment]
现在首页在不同分辨率下面有不同的显示形态。比如这个是800左右宽的分辨率下。

![0000](https://cloud.githubusercontent.com/assets/12635228/8266608/382661b4-176a-11e5-82bb-4391133f20d0.jpg)

**Comment by barrowcom** [comment]
其实这个样子就蛮好，就是BARROW这个LOGO，应该去左上角，然后这个轮播的大图，轮播的大图支持960*500的分辨率就好,然后下面就是登录信息了，这个登录信息，可否把输入用户名和密码的这个框，包括登录的这个按钮，不要按照浏览器的分辨率进行自适应拉长的，没必要拉那么长，就标准尺寸，然后居中就挺好的。

**Comment by barrowcom** [comment]
现在右下角的“首页”，可以把内容改成“官方”我们设置一个链接到官方网站，然后快递查询是要保留的，协议里有写。“购买”可以指向淘宝店，或者我们后期开设的在线订购平台的地址，这个“博客”就改成“帮助”就好了，我知道这个首页和后台配置你还没完成，还在弄，我只是把我们需要的内容讲出来，你做变更的时候有个方向性，争取一次过。

**Comment by barrowcom** [comment]
现在右下角的“首页”，可以把内容改成“官方”我们设置一个链接到官方网站

这句我打错了一个字，不是官方，是官网

**Comment by xwqb** [comment]
我把登录页面都做成配置的话，应该可以解决你说的这些问题！这个登录文本和登录按钮的自适应我取消掉就行了

**Comment by barrowcom** [comment]
大图分辨率1200*400，登录窗靠下居中，LOGO右下角，博客改帮助。OK，
