### ISSUE TITLE
通知里面的标题带有指向性

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#45]
现在通知消息是“有订单需要生产，请注意查看”日期，后面有个操作钮，是标记是否已读的，这里的通知标题内容可否改成“有订单需要审核，请注意查看”然后这个标题是可以点击的，点击了以后直接就能到达这个订单详情页进行操作了，这样比较合理一些

  就好像有人通知大家停车场有车违规停车了需要挪车，但是又不告诉大家车牌号，只能去停车场自己看。不太科学。

**Comment by barrowcom** [comment]
就是给通知标题内容一个链接指向，直接连接到订单详情页了。

**Comment by xiaoweiqb** [comment]
这个只能做到跳转到订单页面，无法跟踪到精准的一条！
