### ISSUE TITLE
客户端查看订单详情的一些补充细节

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#46]
![ll1](https://cloud.githubusercontent.com/assets/12635228/8265956/77fade1c-1744-11e5-8a5e-8dd004986f6f.png)

上图是现在模拟客户查看订单详情的具体内容

请在订购的产品那一列，数量后面，把金额也显示出来，这里说的金额，是该行的产品总金额，比如数量10，单价5元，那么金额是50，这个我们后台应该是有数据统计的，这里他它显示出来

还有就是在这个页面把运费、货款合计金额、订单总额（就是加上运费的所有的钱的总数）显示出来

另外现在有运单号码可以查看，但是缺少“承运公司”的名称显示

**Comment by barrowcom** [comment]
承运公司可以就写“运输方式”，然后数据就套用下单时候选择的运费模板的名称就出来了。

**Comment by xwqb** [comment]
哥们，估计你还没明白我的意思，在列表中已经列出来 了产品金额，运输方式，以及货款总金额等信息！后台是因为要修改所以显示出来了，这里再列表中已经能一目了然，在详情里面只是能看到收货的一些信息，跟产品信息，如果你确定要改，我也没办法，因为这个不是功能性的问题！你确定要改么？
