### ISSUE TITLE
物流查询的问题

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#49]
![Uploading bh.png…]()

今天填写了一个真实单号，但是查询状态是参数错误

**Comment by barrowcom** [comment]
还有我想知道这个物流的模板和这个查快递的软件之间是怎么联系的，就是后台怎么对我填写的物流模板名称和快递查询系统进行匹配对接的呢？

**Comment by barrowcom** [comment]
![bh](https://cloud.githubusercontent.com/assets/12635228/8266448/7f5ee924-1761-11e5-9436-a735e4e3d3fc.png)

**Comment by xwqb** [comment]
这个是我忘了给你说，这个快递100有个物流代码，也就是说每个物流都有一个代码，要再添加运费模板的时候填写，如果没有填写这个物流代码，就会显示参数错误，明天我把这个物流代码给你，上面支持的就可以！
