### ISSUE TITLE
运费模板

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#5]
运费模板的页面，有模板名称，模板说明和模板价格，发货方式一般是这样进行计算的，比如我们常用的几种物流发货方式，如中通快递，他们是根据不同的区域划分不同的价格，计费方式为（首重单价）+（续重单价*每公斤）=实际运费，比如发往北京，货物重量20公斤，快递公司按首重8元，续重2元计费，那么计算公式就是8+（19*2）=46

德邦快递相对比较简单，因为大部分我们都是发送的运费到付，就是运费在客户收货的时候自行支付。

问题就是运费模板主要是针对的选择快递发货的用户，客户选择不同的收货地址，会相应的去对应模板价格计算生成实际运费，现在运费模板的功能我看没实现运费计算的功能。

**Comment by xwqb** [comment]
因为当时你说的是在商品里面添加运费模板，所以我不知道到底是在哪里计算，如果是用户提交订单时选择模板的话，那就好办，如果是在商品里面添加运费模板的话，肯定不对的
