### ISSUE TITLE
用户订货端产品列表的显示BUG

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#51]
在现在建立的产品列表里面，在“顶级类目”下面建立的“接头类目”下，又建立了很多小类，在其中一个“多通型接头“小类里面，我们建立有一个产品。

在实际操作演练中发现，点击类目的”全部“，这个产品可以在右侧显示出来，

点击”接头“这个大类，产品显示不出来

点击”多通型接头“这个小类，产品能显示出来

总结发现，在具体商品所在小类的所属上一级类里，商品会无法显示。

**Comment by xwqb** [comment]
恩，这个没办法，你给我的那个eshop的后台也是这样的哈，这个只有这样了哦！
