### ISSUE TITLE
产品表格的内容、以及属性和排版需要修改的地方

### ISSUE THREAD

**Issue by zhongjia** [xwqb/barrow#6]
表格需要修改的地方，红色字体代表需要修改的表格内容，其中规格这里就是我们说的型号，我在上传的时候发现规格和库存都是必填项，请在设置功能里面增加一个约束功能，就是关于库存这里的，可以启动核验库存功能，那么库存0时，客户将无法添加到购物车，也可以关闭核验库存功能，那么库存0时，客户仍然可以添加到购物车，因为我们现在库存管理无法做到100%同步准确，所以之前我们沟通的时候，有提到客户下单我们人工审核，就是为了避免库存不准确造成的麻烦，这个地方请做相应修改。

**Comment by zhongjia** [comment]
![01](https://cloud.githubusercontent.com/assets/12555691/7782845/03250e6a-015e-11e5-8235-934c373bac36.jpg)

**Comment by xwqb** [comment]
因为进销存软件的库存一直都是个问题，就连淘宝，京东这样的网站的库存都是不准确的，这样吧，如果产品的库存为0，那么就不允许添加商品，这样我觉得比较好，至于库存，这个也只是一个大概
