### ISSUE TITLE
右侧的在线客服激活范围问题

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#63]
虽然图片做了部分透明的效果来缩小这个“在线客服”的像素尺寸，但是测试发现实际那些透明的位置，仍然鼠标放上去还是会把它激活出来，能不能在网页上变更一下激活的范围，

**Comment by xiaoweiqb** [comment]
我把这个做成点击的吧！

**Comment by xiaoweiqb** [comment]
如果要关闭直接点击悬浮框到其他位置就可以关闭了！

**Comment by barrowcom** [comment]
行
