### ISSUE TITLE
客户提交订单时候的一个问题

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#71]
确认提交订单的时候如果双击，会重复生成2个相同的订单，这种情况多存在于电脑运行慢或网络慢的时候客户着急点了2次的时候，就被重复提交了，这种重复提交的订单，会在网站平台里看到2个一模一样的订单，但是在管理后台，这种2个一样的订单，只有一个可以有效的导出数据订单数据表格，另外一个导出的时候是空的表格。

  现在要处理的就是不要出现这种重复提交的订单出来。

**Comment by barrowcom** [comment]
现在测试下订单的时候短时间连续点击提交订单，仍然会生成多个重复订单。

**Comment by barrowcom** [comment]
回车的方式提交订单有办法解决这个双击多击的问题吗？

**Comment by xiaoweiqb** [comment]
不是已经解决了吗？

**Comment by xiaoweiqb** [comment]
现在回车已经无效了
