### ISSUE TITLE
将默认分组做到类目的最下方

### ISSUE THREAD

**Issue by barrowcom** [xwqb/barrow#77]
将“默认分组”改名为“其他未分类”，并将他锁定在最下方，始终在所有类的最下面

**Comment by xiaoweiqb** [comment]
你现在是自己把其他的一些分组放到默认分组里面了
你只需要自己把默认分组里面的组名提改到外面来就行了

**Comment by barrowcom** [comment]
都放到外面了，不过顺序上，默认分组还是不在最下
